### ISSUE TITLE
просьба проверить тестовое задание

### ISSUE THREAD

**Issue by yuristrelets** [yuristrelets/wysiwig-task#1]

**Comment by JSMonk** [comment]
Здравствуйте, Юрий.

Комбинация стилей не работает:

https://user-images.githubusercontent.com/10776615/106333694-e5cb0680-6291-11eb-871e-ffed010d14d6.mov

**Comment by yuristrelets** [comment]
@JSMonk Добрый день, спасибо.
В последний момент переделывал копирование/вырезание и сломал.

Исправил.

**Comment by JSMonk** [comment]
Здравствуйте, Юрий.
Все хорошо, задание принято.

Можно Вашу почту (если подписаны были на Patreon - то ту же что и на патреоне) и telegram-контакт (номер или ник, все-равно) для дублирования сообщений.

Пройдет некоторое количество времени (мы сдвимгаем старт на 8 февраля) и Вы получите ссылку на оплату и мы сообщим Вам дальнейшие шаги.

Хорошая работа 👍

**Comment by yuristrelets** [comment]
Добрый вечер, Артем.
Спасибо!

yuristrelets@gmail.com
@styv2k
